import type { Faculty } from './types';

export const faculty: Faculty[] = [
  {
    id: 1,
    name: 'Dr. Evelyn Reed',
    designation: 'Professor',
    department: 'History',
    college: 'Summit College of Arts & Sciences',
    qualifications: 'Ph.D. in Ancient History',
    bio: 'Dr. Reed is a renowned historian specializing in ancient civilizations. Her research has been published in numerous academic journals.',
    avatar: 'https://placehold.co/100x100.png',
  },
  {
    id: 2,
    name: 'Dr. Marcus Chen',
    designation: 'Associate Professor',
    department: 'Computer Science',
    college: 'Pinnacle Institute of Technology',
    qualifications: 'Ph.D. in Artificial Intelligence',
    bio: 'Dr. Chen leads the AI research division and is a leading expert in machine learning and neural networks.',
    avatar: 'https://placehold.co/100x100.png',
  },
  {
    id: 3,
    name: 'Dr. Anita Desai',
    designation: 'Professor',
    department: 'Finance',
    college: 'Apex School of Business',
    qualifications: 'Ph.D. in Economics',
    bio: 'With over 20 years of experience in financial markets, Dr. Desai provides students with invaluable industry insights.',
    avatar: 'https://placehold.co/100x100.png',
  },
  {
    id: 4,
    name: 'Dr. Samuel Greene',
    designation: 'Assistant Professor',
    department: 'Fine Arts',
    college: 'Summit College of Arts & Sciences',
    qualifications: 'M.F.A. in Sculpture',
    bio: 'An award-winning artist, Dr. Greene inspires students to push creative boundaries and develop their artistic voice.',
    avatar: 'https://placehold.co/100x100.png',
  },
  {
    id: 5,
    name: 'Dr. Lena Petrova',
    designation: 'Professor',
    department: 'Data Science',
    college: 'Pinnacle Institute of Technology',
    qualifications: 'Ph.D. in Statistics',
    bio: 'Dr. Petrova\'s work on big data analytics has been instrumental in shaping the curriculum and research at Pinnacle.',
    avatar: 'https://placehold.co/100x100.png',
  },
  {
    id: 6,
    name: 'Dr. Kenji Tanaka',
    designation: 'Professor',
    department: 'Marketing',
    college: 'Apex School of Business',
    qualifications: 'Ph.D. in Marketing',
    bio: 'Dr. Tanaka is a leading expert on consumer behavior and digital marketing strategies.',
    avatar: 'https://placehold.co/100x100.png',
  },
];
